---
- name: Install apache2 on ubuntu server
  hosts: ubuntu
  become: true

  tasks:
  -  name: Installing apche2 
     apt:
      name: apache2
      state: present

  - name: Start apache2 
    service:
      name: apache2
      state: started
