- name: This Playbook Install Packages
  hosts: amazon 
  become: true

  tasks:
  - name: Install Package
    yum: 
      name: [ 'git' , 'make' , 'gcc' , 'telnet' , 'gzip' ]
      state: installed 
